### PR TITLE
added support for Django REST Framework

### LINKED ISSUE #44: old-style-class / Old-style class defined in Django REST Framework
I am using the ModelSerializer in Django REST Framework and pylint-django is marking the following code as old-style-class:

class MySerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel

### PR DESCRIPTION
**Pull request by lfrodrigues**
This adds support for DRF and fixes #44 
Had to update test suit a bit, not sure this was the best way but works.

### CODE REVIEW

**Comment by carlio** [comment]
Looks like coveralls wanted to be extra sure about this one :)

Thanks for the PR!

**Comment by lfrodrigues** [comment]
Thanks for merging, when will you be making a release with this?

**Comment by carlio** [comment]
I'll check this evening in case there are any small bugfixes I can include, then do the release tonight.

**Comment by cancan101** [comment]
The exclude for `Meta` being an old school class should be on `BaseSerializer` no `ModelSerializer. BaseSerializers can have Meta too: https://github.com/tomchristie/django-rest-framework/blob/8c1365e315256f892dced348cf485bf966429596/rest_framework/serializers.py#L132

**Pull request merged**
