### PR TITLE
Add support of mongoengine module.

### PR DESCRIPTION
**Pull request by goldan**
Prevent 'no-member' errors for Document._meta, objects, id/pk, save and errors.

### CODE REVIEW

**Comment by anentropic** [comment]
thanks for this, it's exactly what I needed!

mongoengine is not specific to Django though, this belongs in its own plugin rather than here IMHO

**Comment by anentropic** [comment]
suggested change:  `objects = type`  (instead of `None`)

code like this is valid in mongoengine:
`uk_users = User.objects(country='uk')`

without the change above pylint complains that "objects is not callable"

**Comment by nedbat** [comment]
Agreed that this good thing doesn't belong in a Django plugin.

**Comment by goldan** [comment]
Agreed, though I don't feel like creating a new plugin for 15 lines of code... that's why I posted it here.

**Comment by carlio** [comment]
Awesome stuff! Sorry for delay!

**Pull request merged**
