### PR TITLE
ugettext_lazy().format raises E1101

### LINKED ISSUE #80: ugettext_lazy('').format
Thanks for this great extension.
Currently `pylint` with `pylint-django` returns error `pylint: [no-member] Instance of '__proxy__' has no 'format' member` for something like `ugettet_lazy('').format`.
I fixed it by changing `ugettext_lazy = lambda x: None` to `ugettext_lazy = lambda x: ''` in file `pylint_django/transforms/transforms/django_utils_translation.py`. Is it alright?

### PR DESCRIPTION
**Pull request by canarduck**
Fixes #80

### CODE REVIEW

**Comment by Lynoure** [comment]
Cool that someone is working for this!

**Comment by horejsek** [comment]
When we can expect this feature to be released? :-)

**Comment by canarduck** [comment]
@horejsek well, due to changes on pylint (see https://github.com/PyCQA/pylint/issues/1438#issue-223471173) some required methods are not available anymore, which is why travis tests are failing (see above).

This PR https://github.com/landscapeio/pylint-django/pull/98 provides a workaround, but is not merged yet, so....

**Comment by atodorov** [comment]
Merged manually as part of #113, thanks.

**Pull request closed without merging**
